#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.C28_float{1,0,20.2,2
#
biosConfigCPU2.x28FP: package/cfg/biosConfigCPU2.x28FP.mak

clean::
	-$(RM) package/cfg/biosConfigCPU2.x28FP.mak
